replace github.com/dgrijalva/jwt-go with golang-jwt
vmware-tanzu/tanzu-framework pull request #1266
Opened 2021-12-01 00:48 UTC by pgandigesang

Signed-off-by: Prajwal <pgandigesang@vmware.com>

### What this PR does / why we need it
Dependabot is flagging github.com/dgrijalva/jwt-go with high-severity. No fix version is available and the recommended fix is to move to https://github.com/golang-jwt/jwt which is community maintained clone of jwt-go.

### Which issue(s) this PR fixes

Fixes #715 

### Describe testing done for PR

Logged into TMC server and checked if all the token claims are parsed properly.

### Release note

```release-note
Replacing the github.com/dgrijalva/jwt-go with golang-jwt.
```

### PR Checklist

- [yes] Squash the commits into one or a small number of logical commits
      
- [yes] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [yes] Ensure PR contains terms all contributors can understand and links all contributors can access

### Additional information

#### Special notes for your reviewer

2021-12-01 00:56 UTC, vuil commented
@pgandigesang The linter is reporting the addons/go.sum also needs updating

2021-12-01 01:44 UTC, vuil approved these changes
LGTM, thanks!

2021-12-01 04:13 UTC, vuil requested changes
There are some unit test failures as well (TestParseToken_MissingUsername)

2021-12-03 20:32 UTC, vijaykatam approved these changes

2021-12-06 17:23 UTC, vuil approved these changes

2021-12-06 17:23 UTC, merged