Update docs to use/download smaller sized artifacts for cli installation which excludes plugin binaries
vmware-tanzu/tanzu-framework pull request #1447
Opened 2022-01-04 22:46 UTC by anujc25

### What this PR does / why we need it
- This PR updates the installation documents to use small tarball/zip
  the file containing just the CLI to install the Tanzu CLI
- Also adds location to download admin-plugins from release artifacts

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

### Release note

```release-note

```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### Additional information

#### Special notes for your reviewer

2022-01-05 07:55 UTC, navidshaikh requested changes
Since there are multiple artifacts on the release page, I think it'd be helpful to add a table in getting-started document describing the filename and one liner description for each artifact.

2022-01-05 07:55 UTC, navidshaikh commented on docs/cli/getting-started.md
> +With [v0.14.0](https://github.com/vmware-tanzu/tanzu-framework/releases/tag/v0.14.0) release, more artifacts are getting published to allow users to download only the artifacts that are required for
```suggestion
With [v0.14.0](https://github.com/vmware-tanzu/tanzu-framework/releases/tag/v0.14.0) release, the artifacts are better categorised and published to allow users to download and configure per recommended and alternate methods.
```

2022-01-05 07:55 UTC, navidshaikh commented on docs/cli/getting-started.md
> +The API driven plugin discovery feature is enabled as default method to install the plugins. So, most of the users will just need to install binary for Tanzu CLI. The plugins can be downloaded with `
```suggestion
The API driven plugin discovery feature is enabled as default method to install the plugins. So, most of the users will just need to install the Tanzu CLI binary. The plugins can be installed and configured with `tanzu plugin sync` command. Learn more about this feature in the [design docs](../design/context-aware-plugin-discovery-design.md).
```

2022-01-05 07:55 UTC, navidshaikh commented on docs/cli/getting-started.md
> +- Download the latest tanzu-cli from [release](https://github.com/vmware-tanzu/tanzu-framework/releases/latest). (`tanzu-cli-darwin-amd64.tar.gz`,  `tanzu-cli-linux-amd64.tar.gz`)
```suggestion
- Download the latest tanzu-cli tarball from [release](https://github.com/vmware-tanzu/tanzu-framework/releases/latest) page (`tanzu-cli-darwin-amd64.tar.gz` or `tanzu-cli-linux-amd64.tar.gz`)
```

2022-01-05 07:55 UTC, navidshaikh commented on docs/cli/getting-started.md
> +- Download the latest tanzu-cli from [release](https://github.com/vmware-tanzu/tanzu-framework/releases/latest). (`tanzu-cli-windows-amd64.zip`)
```suggestion
- Download the latest `tanzu-cli-windows-amd64.zip` from [release](https://github.com/vmware-tanzu/tanzu-framework/releases/latest) page
```

2022-01-05 07:55 UTC, navidshaikh commented on docs/cli/plugin_implementation_guide.md
> +1. Download the latest admin plugin tarball or zip file from [release](https://github.com/vmware-tanzu/tanzu-framework/releases/latest). (`tanzu-framework-plugins-admin-linux-amd64.tar.gz`, `tanzu-fr
```suggestion
1. Download the latest admin plugin tarball or zip file from [release](https://github.com/vmware-tanzu/tanzu-framework/releases/latest) page (`tanzu-framework-plugins-admin-linux-amd64.tar.gz` or `tanzu-framework-plugins-admin-darwin-amd64.tar.gz` or `tanzu-framework-plugins-admin-darwin-amd64.tar.gz`) and extract it (using `linux` as example OS for next steps)
```

2022-01-06 09:38 UTC, navidshaikh approved these changes
lgtm!

As mentioned earlier, it'd be helpful to enlist all the artifacts we produce and one liner description of each (can be done in a follow up!).

2022-01-07 00:20 UTC, vuil approved these changes
couple of language nits, should you choose to rebase, but otherwise lgtm.

2022-01-07 00:20 UTC, vuil commented on docs/cli/getting-started.md
> +With [v0.14.0](https://github.com/vmware-tanzu/tanzu-framework/releases/tag/v0.14.0) release, the artifacts are better categorised and published to allow users to download and configure per recommend
```suggestion
With [v0.14.0](https://github.com/vmware-tanzu/tanzu-framework/releases/tag/v0.14.0) release, the artifacts are better categorized and published to allow users to download and configure per recommended and alternate methods.
```
```suggestion
With [v0.14.0](https://github.com/vmware-tanzu/tanzu-framework/releases/tag/v0.14.0) release, the artifacts are better categorised and published to allow users to download and configure per recommended and alternate methods.
```

2022-01-07 00:20 UTC, vuil commented on docs/cli/getting-started.md
> +The API driven plugin discovery feature is enabled as default method to install the plugins. So, most of the users will just need to install the Tanzu CLI binary. The plugins can be installed and con
```suggestion
The API driven plugin discovery feature is enabled as default method to install the plugins. So, most users will just need to install the Tanzu CLI binary. The plugins can be installed and configured with `tanzu plugin sync` command. Learn more about this feature in the [design docs](../design/context-aware-plugin-discovery-design.md).
```
```suggestion
The API driven plugin discovery feature is enabled as default method to install the plugins. So, most of the users will just need to install the Tanzu CLI binary. The plugins can be installed and configured with `tanzu plugin sync` command. Learn more about this feature in the [design docs](../design/context-aware-plugin-discovery-design.md).
```

2022-01-07 00:21 UTC, vuil approved these changes

2022-01-07 09:41 UTC, navidshaikh commented
Logged the issue https://github.com/vmware-tanzu/tanzu-framework/issues/1459 for follow up. Merging this PR.

2022-01-07 09:42 UTC, merged