update TKG CAPV version to v1.1.0
vmware-tanzu/tanzu-framework pull request #1736
Opened 2022-02-25 00:29 UTC by aartij17

### What this PR does / why we need it

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

### Release note

```release-note

```

### PR Checklist

- [ ] Squash the commits into one or a small number of logical commits
      
- [ ] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [ ] Ensure PR contains terms all contributors can understand and links all contributors can access

### Additional information

#### Special notes for your reviewer

2022-02-25 19:18 UTC, srm09 requested changes
There a couple of conflicts in the `go.mod` files. This is still missing the overlay changes for `kube-vip`.

2022-02-25 19:18 UTC, srm09 commented on pkg/v1/providers/infrastructure-vsphere/v1.1.0/infrastructure-components.yaml
> +        image: gcr.io/cluster-api-provider-vsphere/release/manager:v1.1.0
This would need to be reverted back

2022-02-25 19:18 UTC, srm09 commented on pkg/v1/providers/infrastructure-vsphere/v1.1.0/infrastructure-components.yaml
> -          value: ${TKG_NO_PROXY}
The proxy stuff should be added back too.

2022-02-25 21:43 UTC, srm09 requested changes

2022-02-25 21:43 UTC, srm09 commented on pkg/v1/providers/infrastructure-vsphere/v1.1.0/ytt/base-template.yaml
> -              value: "4"
This needs to be reverted back. We need to relax the leader election parameters.

2022-02-25 21:43 UTC, srm09 commented on pkg/v1/providers/infrastructure-vsphere/v1.1.0/ytt/overlay.yaml
> +      value: "2"
Same as above

2022-03-04 19:13 UTC, aartij17 commented
/test

2022-03-04 19:13 UTC, alfredthenarwhal commented
> @aartij17: /test

Tests can be triggered only by the trusted reviewers (users mentioned in CODEOWNERS file).

2022-03-04 19:16 UTC, navidshaikh commented
/test install-vc7

2022-03-04 19:44 UTC, alfredthenarwhal commented
> @navidshaikh:  /test install-vc7
Commit: bc0cbf1

Tests failed! Build no: 1591

2022-03-07 21:38 UTC, aartij17 commented
@alfredthenarwhal I am a little unsure of the reason the build is failing. Any hints/suggestions would be super helpful!

2022-03-08 22:38 UTC, anujc25 commented
Please add some details to the PR description and release note to the PR.

2022-03-08 22:41 UTC, aartij17 commented
> Please add some details to the PR description and release note to the PR.

Done

2022-03-08 23:48 UTC, anujc25 approved these changes

2022-03-09 00:07 UTC, merged