TKGS Validation changes for cluster class use case
vmware-tanzu/tanzu-framework pull request #2586
Opened 2022-06-08 19:40 UTC by chandrareddyp

### What this PR does / why we need it
It disables the legacy validation for the TKGS workload cluster creation if the input config file is cluster class based. 
Also, it disables the TKC Version validation with the CLI version for TKGS legacy cluster creation.
### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR
Create TKGS workload cluster with Cluster Class yaml file
`tanzu cluster create -f TKGSCluster.yaml`

Create TKGS workload cluster with legacy config file
`tanzu cluster create -f legacyConfig.yaml`

### Release note

```release-note

```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### Additional information

#### Special notes for your reviewer

2022-06-08 20:46 UTC, saji-pivotal requested changes

2022-06-08 20:47 UTC, chandrareddyp commented on pkg/v1/tkg/tkgctl/create_cluster_test.go
> +			IsInputFileClusterClassBased, err := ctl.processWorkloadClusterInputFile(&options, false)
I need to add unit test cases, but because of time, I am not doing it now. i will add as part of feature gate changes.

2022-06-08 21:13 UTC, chandrareddyp commented on pkg/v1/tkg/tkgctl/create_cluster.go
> +	if !isInputFileClusterClassBased {
I have updated the code, i have removed the if condition, because I need to do more testing for that, for now I have removed it.

2022-06-08 23:40 UTC, saji-pivotal approved these changes

2022-06-08 23:44 UTC, saji-pivotal commented
@chandrareddyp Can you please add some detail to the testing that was done? What was successful, and what was not...

2022-06-09 00:41 UTC, anujc25 approved these changes

2022-06-09 01:12 UTC, merged