first cut
vmware-tanzu/tanzu-framework pull request #3063
Opened 2022-08-02 21:33 UTC by chandrareddyp

### What this PR does / why we need it

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

### Release note

```release-note

```

### Additional information

#### Special notes for your reviewer

2022-08-03 23:57 UTC, tenczar requested changes
Small fix, then looks good.

2022-08-03 23:57 UTC, tenczar commented on pkg/v1/providers/infrastructure-azure/v1.4.0/cconly/base.yaml
> +    identifier.cc.vmware.com: tanzu-aws-default-0.0.1
```suggestion
    identifier.cc.vmware.com: tanzu-azure-default-0.0.1
```

2022-08-03 23:57 UTC, tenczar commented on packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
> +    identifier.cc.vmware.com: tanzu-aws-default-0.0.1
```suggestion
    identifier.cc.vmware.com: tanzu-azure-default-0.0.1
```

2022-08-04 00:47 UTC, chandrareddyp commented on packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
> +    identifier.cc.vmware.com: tanzu-aws-default-0.0.1
done. thanks.

2022-08-04 00:47 UTC, chandrareddyp commented on pkg/v1/providers/infrastructure-azure/v1.4.0/cconly/base.yaml
> +    identifier.cc.vmware.com: tanzu-aws-default-0.0.1
done. thanks.

2022-08-04 16:25 UTC, tenczar approved these changes
LGTM

2022-08-04 16:34 UTC, anujc25 approved these changes
LGTM. Please file corresponding issue and update the PR description.

2022-08-04 16:52 UTC, merged

2022-08-04 16:58 UTC, chandrareddyp commented
> LGTM. Please file corresponding issue and update the PR description.

https://github.com/vmware-tanzu/tanzu-framework/issues/3077 created. thanks.