Fix the extra space in no_proxy
vmware-tanzu/tanzu-framework pull request #3764
Opened 2022-10-26 21:02 UTC by lubronzhan

### What this PR does / why we need it
Creating management cluster with proxy will fail. Since there are extra space in the no_proxy settings, making the kubeadm command to error out, thus kube-apiserver is not getting correct NO_PROXY value

### Which issue(s) this PR fixes

Fixes #https://github.com/vmware-tanzu/tanzu-framework/issues/3763

### Describe testing done for PR

### Release note

```release-note
Remove extra space in no_proxy in clusterclass template
```

### Additional information

#### Special notes for your reviewer

2022-10-26 21:05 UTC, lubronzhan commented
/test install-vc7

2022-10-26 21:51 UTC, tenczar requested changes
Can we fix this issue in azure/aws as well.

2022-10-26 21:52 UTC, tenczar commented on providers/infrastructure-vsphere/v1.3.1/cconly/base.yaml
> +              Environment="NO_PROXY= {{- list "localhost" "127.0.0.1" ".svc" ".svc.cluster.local" ((list "IPv6" "DualStack" | has .builtin.cluster.network.ipFamily) | ternary  "::1" nil) | concat .ne
Nevermind. I just double checked, for some reason this error only exists in vsphere.

2022-10-26 21:52 UTC, tenczar approved these changes
LGTM

2022-10-26 22:02 UTC, HanFa approved these changes
lgtm

2022-10-27 07:10 UTC, alfredthenarwhal commented
Tests passed! Build no: 3040

2022-10-27 19:16 UTC, lubronzhan commented
/test install-vc7

2022-10-27 19:54 UTC, alfredthenarwhal commented
Tests failed! Build no: 3048

2022-10-28 23:27 UTC, lubronzhan commented
/test install-vc7

2022-10-29 01:41 UTC, alfredthenarwhal commented
Tests failed! Build no: 3060

2022-10-31 18:40 UTC, lubronzhan commented
/test install-vc7

2022-10-31 21:14 UTC, alfredthenarwhal commented
Build failed! Build no: 3072

2022-11-01 05:23 UTC, merged