Registering cleanup Antrea interface
vmware-tanzu/tanzu-framework pull request #4393
Opened 2023-02-15 17:47 UTC by knabben

### What this PR does / why we need it
To ensure the persistence of HNS network Antrea provides a register script to restart the networks after reboot, this patches installs this script on each restart.

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

### Release note

```release-note

```

### Additional information

#### Special notes for your reviewer

2023-02-15 21:35 UTC, lubronzhan approved these changes

2023-02-15 21:39 UTC, tenczar approved these changes
Powershell is not my forte, but I believe that this is adding a postKubeadmConfig command to modify some registries that will call the cleanup script when necessary. So this look reasonable to me.

2023-02-15 21:56 UTC, knabben commented
> 

We have been using this script on legacy and I tested it here again before opening the PR. The prekubeadm commands are only installing at boot time.

2023-02-15 22:55 UTC, knabben commented
/test install-vc7

2023-02-16 02:18 UTC, knabben commented
//usebom:sandbox/v2.1.1-zshippable/447906785714507732/tkg-compatibility:v12

2023-02-16 03:44 UTC, alfredthenarwhal commented
> @knabben:  /test install-vc7
Commit: 7b9c657

Tests passed! Build no: 4097

2023-02-16 05:40 UTC, DanielXiao commented on packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
> +      - op: add
Could you hold on this PR to Halifax? It triggers rollout during cc package upgrade.

2023-02-16 05:41 UTC, DanielXiao requested changes
Could you hold on this PR to Halifax? It triggers rollout during cc package upgrade.

2023-06-19 19:57 UTC, knabben commented
already moved downstream

2023-06-19 19:57 UTC, closed without merging