Implement plugin discovery source CRUD command for context aware CLI
vmware-tanzu/tanzu-framework pull request #950
Opened 2021-10-21 23:47 UTC by anujc25

### What this PR does / why we need it
- Implements `tanzu plugin source add/list/update/delete` commands
- Currently, supported discovery types are oci and local
- Add newly added noun, flag to cli-wordlist.yml file

### Which issue(s) this PR fixes

Fixes #947

### Describe testing done for PR

- Manual testing by adding/listing/updating/deleting discovery source

### Release note

```release-note
Implement CLIPlugin discovery source CRUD commands for managing discovery sources
```

### PR Checklist

- [x] Squash the commits into one or a small number of logical commits
      
- [x] Use good commit [messages](https://github.com/vmware-tanzu/tanzu-framework/blob/main/CONTRIBUTING.md)
- [x] Ensure PR contains terms all contributors can understand and links all contributors can access

### Additional information

#### Special notes for your reviewer

2021-11-03 00:16 UTC, anujc25 commented
> would `source` be a better noun than `discovery`?

As discussed in #947, I have updated the noun to `source`.

2021-11-05 00:07 UTC, imikushin requested changes
A few comments to make code simpler and more testable.

Also, please add unit tests for all new functionality.

2021-11-05 00:07 UTC, imikushin commented on pkg/v1/cli/command/core/repo.go
> +func init() { //nolint:dupl
Add explaining comment, e.g. ` // the package has multiple files with an init() function`. Perhaps even on the same line.

2021-11-08 17:29 UTC, vuil approved these changes
Lgtm. Just a nit on the doc.

2021-11-08 17:29 UTC, vuil commented on docs/cli/cli-architecture.md
> +        path: standalone
nit: if you need to update, updating the path value to better match L110 will be less confusing.

2021-11-08 23:41 UTC, imikushin commented on pkg/v1/cli/command/core/discovery_source.go
> +	} else {
Thanks for extracting this as a separate function. 

nit: This would look clearer as a `switch` statement.

2021-11-08 23:55 UTC, imikushin commented on pkg/v1/cli/command/core/discovery_source.go
> +		cfg.ClientOptions.CLI.DiscoverySources = newDiscoverySources
This one hasn't been addressed :(

Please refactor consistent with `deleteDiscoverySource()` and `addDiscoverySource()`

2021-11-09 00:00 UTC, imikushin reviewed
A couple comments still un-addressed. Otherwise looks good!

2021-11-09 01:28 UTC, anujc25 commented on pkg/v1/cli/command/core/discovery_source.go
> +		cfg.ClientOptions.CLI.DiscoverySources = newDiscoverySources
done. Refactored and added unit tests

2021-11-09 01:54 UTC, imikushin approved these changes

2021-11-09 02:32 UTC, merged